name: pedigree_manager
description: A pedigree animal management, tracking, and genetic breeding suggestion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  intl: ^0.19.0
  fl_chart: ^0.66.0
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  collection: ^1.18.0
  csv: ^6.0.0
  file_picker: ^6.1.1
  excel: ^4.0.3
  pdf: ^3.10.7
  printing: ^5.12.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"
