import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/models.dart';

/// Generates a PDF pedigree certificate for an animal.
class PedigreePdfService {
  /// Generates a pedigree PDF and returns the bytes.
  /// [animal] is the subject animal.
  /// [pedigree] is the pedigree tree (up to 4 generations).
  /// [allAnimals] is used to resolve parent names.
  static Future<Uint8List> generateCertificate({
    required Animal animal,
    required List<Animal> allAnimals,
    int generations = 4,
  }) async {
    final pdf = pw.Document(
      title: '${animal.name} - Pedigree Certificate',
      author: 'Pedigree Manager',
    );

    // Build ancestor map
    final ancestors = <String, Animal>{};
    for (final a in allAnimals) {
      ancestors[a.id] = a;
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(24),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // Header
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#2E7D32'),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Pedigree Certificate',
                    style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  pw.Text(
                    'Pedigree Manager',
                    style: pw.TextStyle(
                      fontSize: 12,
                      color: PdfColor.fromHex('#C8E6C9'),
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 12),

            // Animal info row
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400),
                borderRadius: pw.BorderRadius.circular(4),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _infoCol('Name', animal.name),
                  _infoCol('Breed', animal.breed),
                  _infoCol('Species', animal.species),
                  _infoCol('Sex', animal.sex == Sex.male ? 'Male' : animal.sex == Sex.female ? 'Female' : 'Unknown'),
                  _infoCol('DOB', animal.dateOfBirth != null
                      ? '${animal.dateOfBirth!.day}/${animal.dateOfBirth!.month}/${animal.dateOfBirth!.year}'
                      : 'Unknown'),
                  _infoCol('Reg#', animal.registrationNumber ?? '-'),
                ],
              ),
            ),
            pw.SizedBox(height: 12),

            // Pedigree tree
            pw.Expanded(
              child: _buildPedigreeTree(animal, ancestors, generations),
            ),

            // Footer
            pw.SizedBox(height: 8),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by Pedigree Manager',
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                ),
                pw.Text(
                  'Date: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                ),
              ],
            ),
          ],
        ),
      ),
    );

    return pdf.save();
  }

  static pw.Widget _infoCol(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label,
            style: pw.TextStyle(
                fontSize: 8,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey600)),
        pw.SizedBox(height: 2),
        pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
      ],
    );
  }

  static pw.Widget _buildPedigreeTree(
    Animal animal,
    Map<String, Animal> ancestors,
    int maxGen,
  ) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        // Gen 0: Subject
        pw.Expanded(
          flex: 2,
          child: pw.Center(
            child: _animalCell(animal, isSubject: true),
          ),
        ),
        // Gen 1: Parents
        pw.Expanded(
          flex: 2,
          child: pw.Column(
            mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
            children: [
              _animalCell(_resolve(animal.sireId, ancestors), label: 'Sire'),
              _animalCell(_resolve(animal.damId, ancestors), label: 'Dam'),
            ],
          ),
        ),
        // Gen 2: Grandparents
        if (maxGen >= 3)
          pw.Expanded(
            flex: 3,
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
              children: [
                _grandparentCell(animal.sireId, ancestors, 'Sire\'s Sire'),
                _grandparentCell(animal.sireId, ancestors, 'Sire\'s Dam', isDam: true),
                _grandparentCell(animal.damId, ancestors, 'Dam\'s Sire'),
                _grandparentCell(animal.damId, ancestors, 'Dam\'s Dam', isDam: true),
              ],
            ),
          ),
        // Gen 3: Great-grandparents
        if (maxGen >= 4)
          pw.Expanded(
            flex: 4,
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
              children: _buildGreatGrandparents(animal, ancestors),
            ),
          ),
      ],
    );
  }

  static List<pw.Widget> _buildGreatGrandparents(
    Animal animal,
    Map<String, Animal> ancestors,
  ) {
    final results = <pw.Widget>[];
    // For each grandparent, show their sire and dam
    final parents = [animal.sireId, animal.damId];
    for (final parentId in parents) {
      final parent = parentId != null ? ancestors[parentId] : null;
      final grandparents = [parent?.sireId, parent?.damId];
      for (final gpId in grandparents) {
        final gp = gpId != null ? ancestors[gpId] : null;
        results.add(_smallCell(_resolve(gp?.sireId, ancestors)));
        results.add(_smallCell(_resolve(gp?.damId, ancestors)));
      }
    }
    return results;
  }

  static Animal? _resolve(String? id, Map<String, Animal> ancestors) {
    if (id == null) return null;
    return ancestors[id];
  }

  static pw.Widget _grandparentCell(
    String? parentId,
    Map<String, Animal> ancestors,
    String label, {
    bool isDam = false,
  }) {
    final parent = parentId != null ? ancestors[parentId] : null;
    final gpId = isDam ? parent?.damId : parent?.sireId;
    final gp = gpId != null ? ancestors[gpId] : null;
    return _animalCell(gp, label: label, small: true);
  }

  static pw.Widget _animalCell(Animal? animal,
      {String? label, bool isSubject = false, bool small = false}) {
    final bgColor = isSubject
        ? PdfColor.fromHex('#E8F5E9')
        : PdfColor.fromHex('#F5F5F5');
    final borderColor = isSubject
        ? PdfColor.fromHex('#2E7D32')
        : PdfColors.grey400;

    return pw.Container(
      margin: const pw.EdgeInsets.all(2),
      padding: pw.EdgeInsets.all(small ? 3 : 6),
      decoration: pw.BoxDecoration(
        color: bgColor,
        border: pw.Border.all(color: borderColor, width: isSubject ? 2 : 0.5),
        borderRadius: pw.BorderRadius.circular(3),
      ),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          if (label != null)
            pw.Text(label,
                style: pw.TextStyle(
                    fontSize: small ? 5 : 7,
                    color: PdfColors.grey500,
                    fontWeight: pw.FontWeight.bold)),
          pw.Text(
            animal?.name ?? 'Unknown',
            style: pw.TextStyle(
              fontSize: small ? 7 : (isSubject ? 12 : 9),
              fontWeight:
                  isSubject ? pw.FontWeight.bold : pw.FontWeight.normal,
            ),
            maxLines: 1,
          ),
          if (animal != null && !small) ...[
            pw.Text(
              animal.breed,
              style: pw.TextStyle(fontSize: small ? 5 : 7, color: PdfColors.grey600),
              maxLines: 1,
            ),
            if (animal.registrationNumber != null &&
                animal.registrationNumber!.isNotEmpty)
              pw.Text(
                animal.registrationNumber!,
                style: const pw.TextStyle(fontSize: 6, color: PdfColors.grey500),
                maxLines: 1,
              ),
          ],
        ],
      ),
    );
  }

  static pw.Widget _smallCell(Animal? animal) {
    return pw.Container(
      margin: const pw.EdgeInsets.all(1),
      padding: const pw.EdgeInsets.all(2),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#FAFAFA'),
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
        borderRadius: pw.BorderRadius.circular(2),
      ),
      child: pw.Text(
        animal?.name ?? '?',
        style: const pw.TextStyle(fontSize: 6),
        maxLines: 1,
      ),
    );
  }
}
